on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Checkout code
        uses: actions/checkout@master
      - name: Cache Maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Generate CHANGELOG.md
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: ${{ github.ref }}
          due_tag: v0.7.0-0
          since_tag: v0.5.2-2
      - name: Build project
        run: mvn package -Pci -DskipTests -Dassembly.name=GA
      - name: Create SHA file.
        run: (cd release; shasum comixed-app-0.7.0-0-GA.zip > comixed-app-0.7.0-0.GA.zip-sha)
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            release/comixed-release-0.7.0-0-GA.zip
            release/comixed-release-0.7.0-0.GA.zip-sha
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
